spring:
  datasource:
    password: abc123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/listener?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: 10.10.16.2
    port: 98763
    password: goldencis
