spring:
  datasource:
    password: abc123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.169.191:3306/dome?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: 81.70.169.191
    port: 6379
    database: 0
#    password: abc123456

