spring:
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/listener?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
