spring:
  datasource:
    dynamic:
      datasource:
         master:
           password: 123456
           username: root
           driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://localhost:3306/goldencis?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
         slave:
           password: goldencis
           username: root
           driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://10.10.16.230:3306/vops_asset_hub?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false
      primary: master
      strict: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.jvm.multdatasource