package org.example.entity.notifyObject;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 通知人脸对象
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PersonObject {
    String FaceStyle;  //鹅蛋脸",
    String BodyFeature;  //体表特征",
    String PersonDisAppearTime;  //20190212231230",
    int HeightUpLimit; // 180,
    SubImageList SubImageList;  //",
    String IDType;  //111",
    String CapStyle;  //1",
    String Name;  //李四",
    String InjuredDegree;  //1",
    String SkinColor;  //白皙",
    String PersonID;  //330108000011900000010520190218164609123450612345",
    String FacialFeature;  //脸部特征",
    int  HeightLowerLimit; //": 160,
    String Gesture;  //99",
    int RightBtmY; //": 12,
    int RightBtmX; //": 12,
    boolean IsCriminalInvolved; //": 0,
    String Behavior;  //1",
    String TrousersColor;  //1",
    String PhysicalFeature;  //体貌特征",
    String HairStyle;  //1",
    String AppendantDescription;  //附属物描述",
    String GenderCode;  //1",
    String Status;  //1",
    String RespiratorColor;  //1",
    String PersonAppearTime;  //20190212231230",
    String EthicCode;  //01",
    String ResidenceAdminDivision;  //110100",
    int AgeLowerLimit; //": 12,
    String BagColor;  //1",
    String CorpseConditionCode;  //10",
    String DetentionHouseCode;  //123456789",
    boolean IsVictim; //": 0,
    int  LeftTopY; //": 12,
    String MemberTypeCode;  //10",
    int LeftTopX; //": 12,
    String TrousersStyle;  //1",
    String UmbrellaColor;  //1",
    String CoatStyle;  //1",
    boolean IsDriver; //": 0,
    boolean IsForeigner; //": 0,
    String GlassStyle;  //1",
    String DetaineesIdentity;  //1",
    String UsedName;  //李三",
    String NativeCityCode;  //110100",
    String JobCategory;  //123",
    String BodySpeciallMark;  //体表特殊标记",
    String NationalityCode;  //CHN",
    int  AccompanyNumber;//": 2,
    String BodyType;  //微胖",
    String EscapedCriminalNumber;  //01234567890123456789012",
    String BehaviorDescription;  //行为描述",
    String ShoesColor;  //1",
    String CriminalInvolvedSpecilisationCode;  //10",
    boolean IsSuspectedTerrorist; //": 0,
    String ShoesStyle;  //1",
    String CrimeMethod;  //作案手段",
    String SuspectedTerroristNumber;  //1111111111111111111",
    String Appendant;  //附属物",
    boolean IsSuspiciousPerson; //": 0,
    String LocationMarkTime;  //20190212231230",
    String PassportType;  //11",
    String ImmigrantTypeCode;  //11",
    String IDNumber;  //130631199205120111",
    String PersonOrg;  //海康威视",
    String DeviceID;  //33010800001190000001",
    String SourceID;  //33010800001190000001052019021816460912345",
    String TrousersLen;  //1",
    String HabitualMovement;  //1",
    String HairColor;  //1",
    String ScarfColor;  //1",
    int InfoKind; //": 1,
    int AgeUpLimit; //": 12,
    String Alias;  //李二",
    String CoatLength;  //1",
    String GlassColor;  //1",
    String CoatColor;  //1",
    boolean IsDetainees; //": 0,
    String DetaineesSpecialIdentity;  //10",
    String VictimType;  //110",
    String BagStyle;  //1",
    String ChineseAccentCode;  //110200",
    String CapColor;  //1",
    String CrimeCharacterCode;  //100"
}
